### ISSUE TITLE
Consider rewording

### ISSUE THREAD

**Issue by laarchambault** [learn-co-curriculum/js-data-structures-arrays-readme#5]
In the `.splice` section, under "With a Single Argument" heading, consider rewording the following line:
"With a negative 'start' index, the opposite happens:"
to instead read:
"With a negative 'start' index, the starting position counts backward from the end of the array:"

Please read the preceding paragraph. The issue with the first statement in its context: it sounds as if  `days.splice(2)` removes `[Thurs, Fri, Sat, Sun]` and `days.splice(-2)` removes `[Mon, Tues, Wed]`
...which is not true. both remove from the start to the end of the array--they just start in different places.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials to reflect your suggested edit. Thank you for contributing to a learn-co-curriculum repository!

We appreciate your support! 💙
